java {
	sourceCompatibility = targetCompatibility = 23
}

base { 
	archivesName = "${mod_name}-${mod_version}"
}

dependencies {
	modImplementation "net.fabricmc:fabric-loader:"+project.loader_version
}

processResources {
	inputs.property "version", project.mod_version


    filesMatching("fabric.mod.json") {
        expand 'mod_version': project.mod_version
    }
}